- name: Package Managment
  hosts: local
  gather_facts: yes
  become: yes
  tasks:   
  - name: Update package cache
    ansible.builtin.apt:
      update_cache: yes
  
  - name: Install neovim
    ansible.builtin.apt:
      name: neovim
      state: present
