---
- name: Install fonts
  hosts: local
  gather_facts: yes
  tasks:
    - name: Create fonts directory
      ansible.builtin.shell: |
        mkdir -p ~/.local/share/fonts/
      args:
        executable: /bin/bash

    - name: Install Meslo fonts
      ansible.builtin.get_url:
        url: "{{ item }}"
        dest: ~/.local/share/fonts/
      loop:
        - https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Regular.ttf
        - https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold.ttf
        - https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Italic.ttf
        - https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold%20Italic.ttf
